# creating Array from Python object

In [1]:
import numpy as np
a=np.array([1,2,3,4])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


# creating the mulltidimensional arrays

In [2]:
matrix=np.array([[1,2,3],
               [4,5,6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [3]:
print(matrix.ndim) # print the dimension of  array

2


In [4]:
matrix1=np.array([  [1,2,3],
                    [4,5,6],
                    [7,8,9]
                 ])
print(matrix1.ndim)

2


# Initializing with zeros

In [5]:
z=np.zeros((2,3))
print(z)

[[0. 0. 0.]
 [0. 0. 0.]]


# Initializing with ones

In [6]:
one=np.ones((3,2))
print(one)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


# for the range of values

In [7]:
r=np.arange(0,10,2)
print(r)

[0 2 4 6 8]


In [8]:
new_r=np.arange(3,30,4)
print(new_r)

[ 3  7 11 15 19 23 27]


# Evenly Spaced Values

In [9]:
l=np.linspace(0,1,5)
print(l)

[0.   0.25 0.5  0.75 1.  ]


In [10]:
l1=np.linspace(2,4,5)
print(l1)

[2.  2.5 3.  3.5 4. ]


# dtype

In [11]:
arr=np.array([1,2,3],dtype=np.float32)
print(arr)

[1. 2. 3.]


# 2) Array Attributes

In [12]:
arr1=np.array([[1,2,3],[4,5,6]])
print('Shape',arr1.shape)

Shape (2, 3)


In [13]:
print('Size',arr1.size) # size of the arr1

Size 6


In [14]:
print('Dimension',arr1.ndim) # size of the arr1

Dimension 2


In [15]:
print('Data Type',arr1.dtype) # data type of the arr1

Data Type int64


In [16]:
print(arr1.itemsize) # memory used by the one element

8


In [17]:
print(arr1.nbytes) # total memory used ie nbytes=size*itemsize

48


# 3) Indexing and Slicing 

In [18]:
print(arr1[0]) # printing the first element that is first row

[1 2 3]


In [19]:
print(arr1[-1]) # printing the last element that is last row

[4 5 6]


In [20]:
print(arr1[0][1]) # printing the second element inside the first element

2


In [21]:
ar=np.array([10,20,30,40,50,60])
print(ar[1:3])

[20 30]


In [22]:
print(ar[:4])#  print  the elemnts from 0 to 3

[10 20 30 40]


In [23]:
print(ar[::3]) # step slicing with the step 3

[10 40]


# slicing in 2D arrays

In [24]:
print(arr1[0])

[1 2 3]


In [25]:
print(arr1[:,1]) # print all the row but only the second column

[2 5]


In [26]:
print(arr1[:,0]) # print all the row but only the first column

[1 4]


In [27]:
print(arr1[0,1])

2


In [28]:
print(ar[[1,3]])# fancy indexing

[20 40]


In [29]:
print(ar[ar>25])# boolean indexing 

[30 40 50 60]
