In [1]:
import numpy as  np 
flat_pixels=np.arange(12)
print(flat_pixels)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


# 1. Reshaping and Transposing


In [2]:
matrix_3x4=flat_pixels.reshape(3,4) # reshape 1D array into a 3x4 matrix
print('Reshaped to 3x4 Matrix:\n',matrix_3x4)

Reshaped to 3x4 Matrix:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [3]:
trans_matrix=matrix_3x4.T # transpose a matrix
print('Transpose Matrix:\n',trans_matrix)

Transpose Matrix:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [4]:
flat_back=matrix_3x4.flatten()# flattened back a given matrix
print('Flattened Back to 1D:\n',flat_back)

Flattened Back to 1D:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]


# 2. Statistical Operation Along axes

In [5]:
marks=np.array([
    [20,30,45],
    [50,60,75],
    [45,85,90]
])
print('Global median of marks',np.median(marks))
print('---------------------------------------------')
print('Global mean of marks',np.mean(marks))
print('---------------------------------------------')
print('Global standard deviation of marks',np.std(marks))

Global median of marks 50.0
---------------------------------------------
Global mean of marks 55.55555555555556
---------------------------------------------
Global standard deviation of marks 22.662308949301263


In [6]:
print('Mean of marks [axis=0]',np.mean(marks,axis=0)) # gives the mean for each column 
print('------------------------------------------------------------------')
print('Mean of marks [axis=1]',np.mean(marks,axis=1)) # gives the mean for each row

Mean of marks [axis=0] [38.33333333 58.33333333 70.        ]
------------------------------------------------------------------
Mean of marks [axis=1] [31.66666667 61.66666667 73.33333333]


In [7]:
print('std of marks [axis=0]',np.std(marks,axis=0))
print('------------------------------------------------------------------')
print('std of marks [axis=0]',np.std(marks,axis=1))

std of marks [axis=0] [13.12334646 22.48456261 18.70828693]
------------------------------------------------------------------
std of marks [axis=0] [10.27402334 10.27402334 20.13840996]


In [8]:
print('Location of max value is',np.argmax(marks)) # gives the location of  max_value
print('Location of min value is',np.argmin(marks)) # gives the location of  min_value

Location of max value is 8
Location of min value is 0


# 3.Matrix Multiplication

In [9]:
X=np.array([
    [2,3,4],
    [1,3,5]
])
Y=np.array([
    [2,4],
    [1,5],
    [3,6]
])

In [10]:
dot_result=np.dot(X,Y) # Traditional multiplication using dot_product
print(dot_result)

[[19 47]
 [20 49]]


In [11]:
matrix_mult=X@Y# Modern pythonic multiplication
print(matrix_mult)

[[19 47]
 [20 49]]


# 4. Conditional Selection

In [12]:
selection=np.where(marks>80)
print(selection)

(array([2, 2]), array([1, 2]))


In [13]:
raw_layer_outputs = np.array([2.4, -1.5, 0.8, -3.2, 5.1])

# np.where(condition, value_if_true, value_if_false)
relu_outputs = np.where(raw_layer_outputs < 0, 0, raw_layer_outputs)
print("Raw Outputs:", raw_layer_outputs)
print("Activated Outputs (ReLU):", relu_outputs)

Raw Outputs: [ 2.4 -1.5  0.8 -3.2  5.1]
Activated Outputs (ReLU): [2.4 0.  0.8 0.  5.1]
