In [1]:
import numpy as np 
import pandas as pd

In [2]:
df=pd.read_csv('/kaggle/input/datasets/nabinpaaudel/covid-toy/covid_toy.csv')
df.head()

,age,gender,fever,cough,city,has_covid
0,60,Male,103.0,Mild,Kolkata,No
1,27,Male,100.0,Mild,Delhi,Yes
2,42,Male,101.0,Mild,Delhi,No
3,31,Female,98.0,Mild,Kolkata,No
4,65,Female,101.0,Mild,Mumbai,No


In [3]:
from sklearn.impute import SimpleImputer
Si=SimpleImputer()
df['fever']=Si.fit_transform(df[['fever']])

In [4]:
df.isnull().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [5]:
X=df.drop(columns=['has_covid'])
y=df['has_covid']
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)

# Manually

In [6]:
from sklearn.preprocessing import OrdinalEncoder,LabelEncoder,OneHotEncoder

In [7]:
oe=OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough=oe.fit_transform(X_train[['cough']])
X_test_cough=oe.fit_transform(X_test[['cough']])



In [8]:
ohe=OneHotEncoder(drop='first',sparse_output=False)
X_train_gender=ohe.fit_transform(X_train[['gender']])
X_test_gender=ohe.fit_transform(X_test[['gender']])
X_train_city=ohe.fit_transform(X_train[['city']])
X_test_city=ohe.fit_transform(X_test[['city']])



In [9]:
X_train_age=X_train['age'].values
X_test_age=X_test['age'].values

In [10]:
X_train_age,X_test_age

(array([42, 34, 20, 56, 42, 82, 79, 33, 19, 49, 65, 10, 60, 12,  5, 49, 66,
         6, 80, 74, 25, 83,  8, 70, 17, 82, 72, 38, 19,  5, 22, 81, 13, 65,
        23, 44, 73, 47, 31, 34, 15, 51, 68, 27, 18, 46, 19, 24, 60, 59, 49,
        71, 81, 10, 20, 51, 64, 54, 16, 51, 34, 16, 65, 64, 12, 19, 23, 14,
        75, 80, 27, 69, 42, 48, 84,  5, 64, 83, 25, 55]),
 array([14, 69, 26, 65, 27, 40, 38, 24, 73, 69, 82, 50, 71, 47, 11, 34, 83,
        20, 11, 75]))

In [11]:
X_train_fever=X_train['fever'].values
X_test_fever=X_test['fever'].values

In [12]:
X_train_fever

array([101.        ,  98.        , 101.        , 104.        ,
       100.84444444, 102.        , 100.84444444, 102.        ,
       101.        , 101.        ,  99.        ,  98.        ,
        99.        , 104.        , 100.        , 102.        ,
        99.        , 104.        ,  98.        , 102.        ,
       104.        ,  98.        , 101.        , 103.        ,
       104.        , 100.84444444,  99.        , 100.84444444,
       100.        ,  98.        ,  99.        , 101.        ,
       100.        , 101.        ,  98.        , 104.        ,
        98.        , 101.        ,  98.        , 104.        ,
       101.        , 104.        , 101.        , 100.        ,
       104.        , 103.        , 100.        , 102.        ,
       103.        ,  99.        ,  99.        ,  98.        ,
        98.        , 100.        , 100.84444444, 101.        ,
       102.        , 104.        , 103.        , 104.        ,
       100.84444444, 104.        ,  98.        ,  98.  

In [13]:
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [14]:
X_train_age=X_train_age.reshape(-1,1)
X_test_age=X_test_age.reshape(-1,1)
X_train_fever=X_train_fever.reshape(-1,1)
X_test_fever=X_test_fever.reshape(-1,1)


In [15]:
X_train_transformed=np.concatenate((X_train_age,X_train_fever,X_train_gender,X_train_city,X_train_cough),axis=1)
X_test_transformed=np.concatenate((X_test_age,X_test_fever,X_test_gender,X_test_city,X_test_cough),axis=1)

In [16]:
X_train_transformed.shape

(80, 7)

# Use of Column Transformer

In [17]:
from sklearn.compose import ColumnTransformer
transformer=ColumnTransformer(transformers=
                             [
                               ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
                                ('tnf3',OneHotEncoder(drop='first',sparse_output=False),['gender','city'])
                             ],remainder='passthrough')

In [18]:
transformer.fit_transform(X_train).shape

(80, 7)